apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["exit","0"]
      restartPolicy: Never
  backoffLimit: 4